Repository cloud-native-toolkit/terraform-gitops-mongo-ce, pull requests merged in 2022-02, with the labels that each got.

#4 Changes in README and type for gitops repo creation
  .github/scripts/validate-deploy.sh
  README.md
Labels: bug

#5 Adds username to outputs
  main.tf
  outputs.tf
Labels: patch, chore

#7 changes in output for sls module
  README.md
  outputs.tf
  test/stages/stage2-mymodule.tf
  test/stages/stage3-outputs.tf
Labels: enhancement, minor

#8 Sets the service name from the provided variable
  chart/mongo-ce/templates/_helpers.tpl
  chart/mongo-ce/templates/configmap.yaml
  chart/mongo-ce/templates/mongodb-ce.yaml
  main.tf
  module.yaml
  outputs.tf
  variables.tf
Labels: bug, patch

#9 Adds password back to output
  outputs.tf
Labels: bug, patch

#10 added cacrt output value and template updates
  .github/workflows/verify.yaml
  outputs.tf
  test/stages/stage1-cluster.tf
  test/stages/stage3-outputs.tf
  test/stages/variables.tf
  variables.tf
Labels: chore
